version: '3'
services:
  api:
    build:
      context: .
      args:
        - env=production
        - bundle_opts=--clean --jobs 20 --retry 5 --without development test
    image: qurancom_beta:prod-latest
    environment:
      - SECRET_KEY_BASE=abcdefa

